server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 4

spring:
  application:
    name: demo
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/demodb?useUnicode=yes&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PSW:Tokoin@123}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect